#include "static_assets/EmbeddedAssetTable.hpp"

#include "logger/Logger.hpp"

#include <cstring>

namespace static_assets {

static logger::Logger log{"EmbeddedAssetTable"};

// ------------------------------------------------------------
// Linker symbols generated by EMBED_FILES
// ------------------------------------------------------------
extern const uint8_t _binary_index_html_start[] asm("_binary_index_html_start");
extern const uint8_t _binary_index_html_end[] asm("_binary_index_html_end");

extern const uint8_t _binary_app_js_start[] asm("_binary_app_js_start");
extern const uint8_t _binary_app_js_end[] asm("_binary_app_js_end");

extern const uint8_t _binary_style_css_start[] asm("_binary_style_css_start");
extern const uint8_t _binary_style_css_end[] asm("_binary_style_css_end");

extern const uint8_t _binary_favicon_ico_start[] asm("_binary_favicon_ico_start");
extern const uint8_t _binary_favicon_ico_end[] asm("_binary_favicon_ico_end");

// ------------------------------------------------------------
// Static table of embedded assets
// ------------------------------------------------------------
struct AssetEntry {
    const char *path;
    const uint8_t *start;
    const uint8_t *end;
};

static const AssetEntry assets[] = {
    {"/index.html", _binary_index_html_start, _binary_index_html_end},
    {"/app.js", _binary_app_js_start, _binary_app_js_end},
    {"/style.css", _binary_style_css_start, _binary_style_css_end},
	{"/favicon.ico", _binary_favicon_ico_start, _binary_favicon_ico_end},
};

// ------------------------------------------------------------
// Modern API
// ------------------------------------------------------------
const EmbeddedAsset *EmbeddedAssetTable::find(std::string_view path) const {
	// TODO review logging - probably over the top.
	log.debug("find '%.*s'", (int)path.size(), path.data());
	
    for (auto &a : assets) {
        if (path == a.path) {
            static EmbeddedAsset asset;
            asset.data = a.start;
            asset.size = a.end - a.start;
            return &asset;
        }
    }

    log.warn("Asset not found: '%.*s'", (int) path.size(), path.data());
    return nullptr;
}

// ------------------------------------------------------------
// Legacy API
// ------------------------------------------------------------
const uint8_t *EmbeddedAssetTable::find(const char *path, size_t &outSize) const {
    for (auto &a : assets) {
        if (std::strcmp(a.path, path) == 0) {
            outSize = a.end - a.start;
            return a.start;
        }
    }

    log.warn("Asset not found: '%s'", path);
    return nullptr;
}

} // namespace static_assets