#pragma once

#include <string_view>
#include <cstddef>
#include <cstdint>

namespace framework_files {

struct EmbeddedFile {
    const uint8_t* data;
    size_t size;
};

/**
 * Abstract interface for an embedded file table.
 *
 * Both the framework and the application provide concrete subclasses so each
 * can carry its own set of EMBED_FILES linker symbols without name collisions.
 * The framework's implementation is FrameworkFileTable (below); apps implement
 * their own subclass — see main/app/AppFileTable for the worked example.
 */
class EmbeddedFileTable {
public:
    virtual ~EmbeddedFileTable() = default;

    /** Look up a file by its bare path (e.g. "/index.html"). */
    virtual const EmbeddedFile* find(std::string_view path) const = 0;

    /** Legacy overload used by some older call sites. */
    virtual const uint8_t* find(const char* path, size_t& outSize) const = 0;
};

/**
 * Concrete table containing the framework's built-in UI assets.
 * The linker symbols are generated by EMBED_FILES in the framework CMake
 * component and resolved in EmbeddedFileTable.cpp.
 */
class FrameworkFileTable : public EmbeddedFileTable {
public:
    const EmbeddedFile* find(std::string_view path) const override;
    const uint8_t* find(const char* path, size_t& outSize) const override;
};

} // namespace framework_files
