// SPDX-FileCopyrightText: 2026 Jon Irons <jon@irons.ws>
// SPDX-License-Identifier: MIT

#include "framework_files/EmbeddedFileTable.hpp"

#include "logger/Logger.hpp"

#include <cstring>

namespace framework_files {

static logger::Logger log{EmbeddedFileTable::TAG};

// ------------------------------------------------------------
// Linker symbols generated by EMBED_FILES (framework assets)
// Files are pre-compressed with gzip; symbols end in _gz_.
// ------------------------------------------------------------
extern const uint8_t _binary_framework_api_js_gz_start[]       asm("_binary_framework_api_js_gz_start");
extern const uint8_t _binary_framework_api_js_gz_end[]         asm("_binary_framework_api_js_gz_end");

extern const uint8_t _binary_framework_app_js_gz_start[]       asm("_binary_framework_app_js_gz_start");
extern const uint8_t _binary_framework_app_js_gz_end[]         asm("_binary_framework_app_js_gz_end");

extern const uint8_t _binary_framework_common_ui_js_gz_start[] asm("_binary_framework_common_ui_js_gz_start");
extern const uint8_t _binary_framework_common_ui_js_gz_end[]   asm("_binary_framework_common_ui_js_gz_end");

extern const uint8_t _binary_framework_index_html_gz_start[]   asm("_binary_framework_index_html_gz_start");
extern const uint8_t _binary_framework_index_html_gz_end[]     asm("_binary_framework_index_html_gz_end");

extern const uint8_t _binary_framework_modal_js_gz_start[]     asm("_binary_framework_modal_js_gz_start");
extern const uint8_t _binary_framework_modal_js_gz_end[]       asm("_binary_framework_modal_js_gz_end");

extern const uint8_t _binary_framework_router_js_gz_start[]    asm("_binary_framework_router_js_gz_start");
extern const uint8_t _binary_framework_router_js_gz_end[]      asm("_binary_framework_router_js_gz_end");

extern const uint8_t _binary_framework_ui_device_js_gz_start[]   asm("_binary_framework_ui_device_js_gz_start");
extern const uint8_t _binary_framework_ui_device_js_gz_end[]     asm("_binary_framework_ui_device_js_gz_end");

extern const uint8_t _binary_framework_ui_firmware_js_gz_start[] asm("_binary_framework_ui_firmware_js_gz_start");
extern const uint8_t _binary_framework_ui_firmware_js_gz_end[]   asm("_binary_framework_ui_firmware_js_gz_end");

extern const uint8_t _binary_framework_ui_security_js_gz_start[] asm("_binary_framework_ui_security_js_gz_start");
extern const uint8_t _binary_framework_ui_security_js_gz_end[]   asm("_binary_framework_ui_security_js_gz_end");

extern const uint8_t _binary_framework_ui_wifi_js_gz_start[]     asm("_binary_framework_ui_wifi_js_gz_start");
extern const uint8_t _binary_framework_ui_wifi_js_gz_end[]       asm("_binary_framework_ui_wifi_js_gz_end");

// ------------------------------------------------------------
// Static table of framework-owned embedded files
// ------------------------------------------------------------
struct FileEntry {
    const char     *path;
    const uint8_t  *start;
    const uint8_t  *end;
};

static const FileEntry files[] = {
    // Framework UI — paths are relative to the /ui/ prefix, which EmbeddedFileHandler
    // strips before the lookup reaches this table.
    {"/api.js",       _binary_framework_api_js_gz_start,       _binary_framework_api_js_gz_end},
    {"/app.js",       _binary_framework_app_js_gz_start,       _binary_framework_app_js_gz_end},
    {"/common_ui.js", _binary_framework_common_ui_js_gz_start, _binary_framework_common_ui_js_gz_end},
    {"/index.html",   _binary_framework_index_html_gz_start,   _binary_framework_index_html_gz_end},
    {"/modal.js",     _binary_framework_modal_js_gz_start,     _binary_framework_modal_js_gz_end},
    {"/router.js",    _binary_framework_router_js_gz_start,    _binary_framework_router_js_gz_end},
    {"/ui_device.js",   _binary_framework_ui_device_js_gz_start,   _binary_framework_ui_device_js_gz_end},
    {"/ui_firmware.js", _binary_framework_ui_firmware_js_gz_start, _binary_framework_ui_firmware_js_gz_end},
    {"/ui_security.js", _binary_framework_ui_security_js_gz_start, _binary_framework_ui_security_js_gz_end},
    {"/ui_wifi.js",     _binary_framework_ui_wifi_js_gz_start,     _binary_framework_ui_wifi_js_gz_end},
};

// ------------------------------------------------------------
// FrameworkFileTable — concrete implementation
// ------------------------------------------------------------

const framework_files::EmbeddedFile *framework_files::FrameworkFileTable::find(std::string_view path) const {
    log.debug("find '%.*s'", (int) path.size(), path.data());

    for (const auto &entry : files) {
        if (path == entry.path) {
            static EmbeddedFile result;
            result.data       = entry.start;
            result.size       = entry.end - entry.start;
            result.compressed = true;
            return &result;
        }
    }

    log.warn("File not found: '%.*s'", (int) path.size(), path.data());
    return nullptr;
}

const uint8_t *FrameworkFileTable::find(const char *path, size_t &outSize) const {
    for (const auto &entry : files) {
        if (std::strcmp(entry.path, path) == 0) {
            outSize = entry.end - entry.start;
            return entry.start;
        }
    }

    log.warn("File not found: '%s'", path);
    return nullptr;
}

} // namespace framework_files
