#include "framework_files/EmbeddedFileTable.hpp"

#include "logger/Logger.hpp"

#include <cstring>

namespace framework_files {

static logger::Logger log{"EmbeddedFileTable"};

// ------------------------------------------------------------
// Linker symbols generated by EMBED_FILES (framework assets)
// ------------------------------------------------------------
// Embedded UI
extern const uint8_t _binary_framework_api_js_start[]       asm("_binary_framework_api_js_start");
extern const uint8_t _binary_framework_api_js_end[]         asm("_binary_framework_api_js_end");

extern const uint8_t _binary_framework_app_js_start[]       asm("_binary_framework_app_js_start");
extern const uint8_t _binary_framework_app_js_end[]         asm("_binary_framework_app_js_end");

extern const uint8_t _binary_framework_common_ui_js_start[] asm("_binary_framework_common_ui_js_start");
extern const uint8_t _binary_framework_common_ui_js_end[]   asm("_binary_framework_common_ui_js_end");

extern const uint8_t _binary_framework_index_html_start[]   asm("_binary_framework_index_html_start");
extern const uint8_t _binary_framework_index_html_end[]     asm("_binary_framework_index_html_end");

extern const uint8_t _binary_framework_modal_js_start[]     asm("_binary_framework_modal_js_start");
extern const uint8_t _binary_framework_modal_js_end[]       asm("_binary_framework_modal_js_end");

extern const uint8_t _binary_framework_router_js_start[]    asm("_binary_framework_router_js_start");
extern const uint8_t _binary_framework_router_js_end[]      asm("_binary_framework_router_js_end");

extern const uint8_t _binary_framework_styles_css_start[]   asm("_binary_framework_styles_css_start");
extern const uint8_t _binary_framework_styles_css_end[]     asm("_binary_framework_styles_css_end");

extern const uint8_t _binary_framework_ui_device_js_start[]   asm("_binary_framework_ui_device_js_start");
extern const uint8_t _binary_framework_ui_device_js_end[]     asm("_binary_framework_ui_device_js_end");

extern const uint8_t _binary_framework_ui_firmware_js_start[] asm("_binary_framework_ui_firmware_js_start");
extern const uint8_t _binary_framework_ui_firmware_js_end[]   asm("_binary_framework_ui_firmware_js_end");

extern const uint8_t _binary_framework_ui_security_js_start[] asm("_binary_framework_ui_security_js_start");
extern const uint8_t _binary_framework_ui_security_js_end[]   asm("_binary_framework_ui_security_js_end");

extern const uint8_t _binary_framework_ui_wifi_js_start[]     asm("_binary_framework_ui_wifi_js_start");
extern const uint8_t _binary_framework_ui_wifi_js_end[]       asm("_binary_framework_ui_wifi_js_end");

extern const uint8_t _binary__favicon_ico_start[]             asm("_binary__favicon_ico_start");
extern const uint8_t _binary__favicon_ico_end[]               asm("_binary__favicon_ico_end");

// ------------------------------------------------------------
// Static table of framework-owned embedded files
// ------------------------------------------------------------
struct FileEntry {
    const char     *path;
    const uint8_t  *start;
    const uint8_t  *end;
};

static const FileEntry files[] = {
    // Framework UI — paths are relative to the /ui/ prefix, which EmbeddedFileHandler
    // strips before the lookup reaches this table.
    {"/api.js",       _binary_framework_api_js_start,       _binary_framework_api_js_end},
    {"/app.js",       _binary_framework_app_js_start,       _binary_framework_app_js_end},
    {"/common_ui.js", _binary_framework_common_ui_js_start, _binary_framework_common_ui_js_end},
    {"/index.html",   _binary_framework_index_html_start,   _binary_framework_index_html_end},
    {"/modal.js",     _binary_framework_modal_js_start,     _binary_framework_modal_js_end},
    {"/router.js",    _binary_framework_router_js_start,    _binary_framework_router_js_end},
    {"/styles.css",      _binary_framework_styles_css_start,        _binary_framework_styles_css_end},
    {"/ui_device.js",   _binary_framework_ui_device_js_start,   _binary_framework_ui_device_js_end},
    {"/ui_firmware.js", _binary_framework_ui_firmware_js_start, _binary_framework_ui_firmware_js_end},
    {"/ui_security.js", _binary_framework_ui_security_js_start, _binary_framework_ui_security_js_end},
    {"/ui_wifi.js",     _binary_framework_ui_wifi_js_start,     _binary_framework_ui_wifi_js_end},

    {"/favicon.ico",    _binary__favicon_ico_start,             _binary__favicon_ico_end},
};

// ------------------------------------------------------------
// FrameworkFileTable — concrete implementation
// ------------------------------------------------------------

const framework_files::EmbeddedFile *framework_files::FrameworkFileTable::find(std::string_view path) const {
    log.debug("find '%.*s'", (int) path.size(), path.data());

    for (const auto &entry : files) {
        if (path == entry.path) {
            static EmbeddedFile result;
            result.data = entry.start;
            result.size = entry.end - entry.start;
            return &result;
        }
    }

    log.warn("File not found: '%.*s'", (int) path.size(), path.data());
    return nullptr;
}

const uint8_t *FrameworkFileTable::find(const char *path, size_t &outSize) const {
    for (const auto &entry : files) {
        if (std::strcmp(entry.path, path) == 0) {
            outSize = entry.end - entry.start;
            return entry.start;
        }
    }

    log.warn("File not found: '%s'", path);
    return nullptr;
}

} // namespace framework_files
