#include "AppFileTable.hpp"

#include "logger/Logger.hpp"

#include <cstring>

static logger::Logger log{"AppFileTable"};

// ------------------------------------------------------------
// Linker symbols generated by EMBED_FILES in main/CMakeLists.txt
//
// Symbol naming rule: for a file listed in EMBED_FILES as
//   <component_dir>/app/files/app_index.html
// ESP-IDF generates:
//   _binary_app_index_html_start
//   _binary_app_index_html_end
//
// Add a pair of extern declarations here for every file in main/app/files/.
// ------------------------------------------------------------

extern const uint8_t _binary_app_index_html_start[] asm("_binary_app_index_html_start");
extern const uint8_t _binary_app_index_html_end[]   asm("_binary_app_index_html_end");

extern const uint8_t _binary_app_css_start[]        asm("_binary_app_css_start");
extern const uint8_t _binary_app_css_end[]          asm("_binary_app_css_end");

extern const uint8_t _binary_app_js_start[]         asm("_binary_app_js_start");
extern const uint8_t _binary_app_js_end[]           asm("_binary_app_js_end");

// ------------------------------------------------------------
// File table — paths are looked up after EmbeddedFileHandler
// strips the URL prefix (e.g. "/app/ui"), so entries use bare
// names like "/index.html".
// ------------------------------------------------------------

namespace {
struct FileEntry {
    const char     *path;
    const uint8_t  *start;
    const uint8_t  *end;
};

static const FileEntry files[] = {
    {"/index.html", _binary_app_index_html_start, _binary_app_index_html_end},
    {"/app.css",    _binary_app_css_start,        _binary_app_css_end},
    {"/app.js",     _binary_app_js_start,         _binary_app_js_end},
};
} // anonymous namespace

// ------------------------------------------------------------
// AppFileTable implementation
// ------------------------------------------------------------

const framework_files::EmbeddedFile *AppFileTable::find(std::string_view path) const {
    log.debug("find '%.*s'", (int) path.size(), path.data());

    for (const auto &entry : files) {
        if (path == entry.path) {
            static framework_files::EmbeddedFile result;
            result.data = entry.start;
            result.size = entry.end - entry.start;
            return &result;
        }
    }

    log.debug("not found: '%.*s'", (int) path.size(), path.data());
    return nullptr;
}

const uint8_t *AppFileTable::find(const char *path, size_t &outSize) const {
    for (const auto &entry : files) {
        if (std::strcmp(entry.path, path) == 0) {
            outSize = entry.end - entry.start;
            return entry.start;
        }
    }
    return nullptr;
}
