#include "embedded_files/EmbeddedFileTable.hpp"

#include "logger/Logger.hpp"

#include <cstring>

namespace embedded_files {

static logger::Logger log{"EmbeddedFileTable"};

// ------------------------------------------------------------
// Linker symbols generated by EMBED_FILES
// ------------------------------------------------------------
// Embedded UI
extern const uint8_t _binary_embedded_api_js_start[] asm("_binary_embedded_api_js_start");
extern const uint8_t _binary_embedded_api_js_end[] asm("_binary_embedded_api_js_end");

extern const uint8_t _binary_embedded_app_js_start[] asm("_binary_embedded_app_js_start");
extern const uint8_t _binary_embedded_app_js_end[] asm("_binary_embedded_app_js_end");

extern const uint8_t _binary_embedded_common_ui_js_start[] asm("_binary_embedded_common_ui_js_start");
extern const uint8_t _binary_embedded_common_ui_js_end[] asm("_binary_embedded_common_ui_js_end");

extern const uint8_t _binary_embedded_device_control_html_start[] asm("_binary_embedded_device_control_html_start");
extern const uint8_t _binary_embedded_device_control_html_end[] asm("_binary_embedded_device_control_html_end");

extern const uint8_t _binary_embedded_device_info_html_start[] asm("_binary_embedded_device_info_html_start");
extern const uint8_t _binary_embedded_device_info_html_end[] asm("_binary_embedded_device_info_html_end");

extern const uint8_t _binary_embedded_index_html_start[] asm("_binary_embedded_index_html_start");
extern const uint8_t _binary_embedded_index_html_end[] asm("_binary_embedded_index_html_end");

extern const uint8_t _binary_embedded_modal_js_start[] asm("_binary_embedded_modal_js_start");
extern const uint8_t _binary_embedded_modal_js_end[] asm("_binary_embedded_modal_js_end");

extern const uint8_t _binary_embedded_navigation_html_start[] asm("_binary_embedded_navigation_html_start");
extern const uint8_t _binary_embedded_navigation_html_end[] asm("_binary_embedded_navigation_html_end");

extern const uint8_t _binary_embedded_styles_css_start[] asm("_binary_embedded_styles_css_start");
extern const uint8_t _binary_embedded_styles_css_end[] asm("_binary_embedded_styles_css_end");

extern const uint8_t _binary_embedded_ui_js_start[] asm("_binary_embedded_ui_js_start");
extern const uint8_t _binary_embedded_ui_js_end[] asm("_binary_embedded_ui_js_end");

extern const uint8_t _binary_embedded_wifi_html_start[] asm("_binary_embedded_wifi_html_start");
extern const uint8_t _binary_embedded_wifi_html_end[] asm("_binary_embedded_wifi_html_end");

// Top-level UI
extern const uint8_t _binary__favicon_ico_start[] asm("_binary__favicon_ico_start");
extern const uint8_t _binary__favicon_ico_end[] asm("_binary__favicon_ico_end");

// Runtime UI
extern const uint8_t _binary_runtime_index_html_start[] asm("_binary_runtime_index_html_start");
extern const uint8_t _binary_runtime_index_html_end[] asm("_binary_runtime_index_html_end");

// ------------------------------------------------------------
// Static table of embedded files
// ------------------------------------------------------------
struct FileEntry {
    const char *path;
    const uint8_t *start;
    const uint8_t *end;
};

static const FileEntry files[] = {
    // Provisioning UI
	// Embedded UI
    {"/embedded/api.js", _binary_embedded_api_js_start, _binary_embedded_api_js_end},
	{"/embedded/app.js", _binary_embedded_app_js_start, _binary_embedded_app_js_end},
    {"/embedded/common_ui.js", _binary_embedded_common_ui_js_start, _binary_embedded_common_ui_js_end},
	{"/embedded/device_control.html", _binary_embedded_device_control_html_start, _binary_embedded_device_control_html_end},
	{"/embedded/device_info.html", _binary_embedded_device_info_html_start, _binary_embedded_device_info_html_end},
	{"/embedded/index.html", _binary_embedded_index_html_start, _binary_embedded_index_html_end},
    {"/embedded/modal.js", _binary_embedded_modal_js_start, _binary_embedded_modal_js_end},
	{"/embedded/navigation.html", _binary_embedded_navigation_html_start, _binary_embedded_navigation_html_end},
    {"/embedded/styles.css", _binary_embedded_styles_css_start, _binary_embedded_styles_css_end},
	{"/embedded/ui.js", _binary_embedded_ui_js_start, _binary_embedded_ui_js_end},
	{"/embedded/wifi.html", _binary_embedded_wifi_html_start, _binary_embedded_wifi_html_end},

    // Top‑level UI
    {"/favicon.ico", _binary__favicon_ico_start, _binary__favicon_ico_end},

	// Runtime UI
    {"/runtime/index.html", _binary_runtime_index_html_start, _binary_runtime_index_html_end},

};

// ------------------------------------------------------------
// Modern API
// ------------------------------------------------------------
const EmbeddedFile *EmbeddedFileTable::find(std::string_view path) const {
    // TODO review logging - probably over the top.
    log.debug("find '%.*s'", (int) path.size(), path.data());

    for (auto &a : files) {
        if (path == a.path) {
            static EmbeddedFile embedded_file;
            embedded_file.data = a.start;
            embedded_file.size = a.end - a.start;
            return &embedded_file;
        }
    }

    log.warn("File not found: '%.*s'", (int) path.size(), path.data());
    return nullptr;
}

// ------------------------------------------------------------
// Legacy API
// ------------------------------------------------------------
const uint8_t *EmbeddedFileTable::find(const char *path, size_t &outSize) const {
    for (auto &a : files) {
        if (std::strcmp(a.path, path) == 0) {
            outSize = a.end - a.start;
            return a.start;
        }
    }

    log.warn("File not found: '%s'", path);
    return nullptr;
}

} // namespace embedded_files